/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2.irina.spagnuolo;

import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Interfaz extends javax.swing.JFrame {
    private HashTable newTablaHash;
    private ArbolPalabrasAVL newArbolPalabras;
    private HashTable tablaPalabrasClave;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        newTablaHash = new HashTable(200);
        newArbolPalabras = new ArbolPalabrasAVL();
        tablaPalabrasClave = new HashTable(400);
    }
    
    private void ordenarTitulosABC(String[] titulos) {
        for (int i = 0; i < titulos.length - 1; i++) {
            for (int j = 0; j < titulos.length - i - 1; j++) {
                if (titulos[j].compareToIgnoreCase(titulos[j + 1]) > 0) {
                    String temp = titulos[j];
                    titulos[j] = titulos[j + 1];
                    titulos[j + 1] = temp;
                }
            }
        }
    }
    
    private int contarFrecuencia(String texto, String palabra) {
        int contador = 0;
        int index = 0;
        while ((index = texto.indexOf(palabra, index)) != -1) {
            contador++;
            index += palabra.length();
        }
        return contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        BotonAnalizar = new javax.swing.JButton();
        Field1 = new javax.swing.JTextField();
        BotonBuscarPC = new javax.swing.JButton();
        Field2 = new javax.swing.JTextField();
        BotonBucarAutor = new javax.swing.JButton();
        BotonMPC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Proyecto 2");

        BotonAgregar.setBackground(new java.awt.Color(255, 204, 51));
        BotonAgregar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonAnalizar.setBackground(new java.awt.Color(255, 204, 51));
        BotonAnalizar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonAnalizar.setText("Analizar");
        BotonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalizarActionPerformed(evt);
            }
        });

        BotonBuscarPC.setBackground(new java.awt.Color(255, 153, 0));
        BotonBuscarPC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonBuscarPC.setText("Buscar");
        BotonBuscarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarPCActionPerformed(evt);
            }
        });

        BotonBucarAutor.setBackground(new java.awt.Color(255, 153, 0));
        BotonBucarAutor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonBucarAutor.setText("Buscar");

        BotonMPC.setBackground(new java.awt.Color(255, 153, 102));
        BotonMPC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonMPC.setText("Mostrar palabras clave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonAnalizar))
                            .addComponent(BotonMPC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonBucarAutor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonBuscarPC)))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonAgregar)
                        .addComponent(BotonAnalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarPC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBucarAutor))
                .addGap(47, 47, 47)
                .addComponent(BotonMPC)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed

    AgregarResumen agregarR = new AgregarResumen(newTablaHash);

    Resumen resumen = agregarR.cargarArchivo();
    if (resumen == null) return;

    newTablaHash.agregarElem(resumen);

    JOptionPane.showMessageDialog(this, "Resumen agregado correctamente.");
        
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalizarActionPerformed
        String[] titulos = newTablaHash.obtenerTitulos();
        if (titulos.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay investigaciones guardadas.");
            return;
        }

        ordenarTitulosABC(titulos);

        String seleccion = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione la investigación a analizar:",
            "Analizar investigación",
            JOptionPane.PLAIN_MESSAGE,
            null,
            titulos,
            titulos[0]);

        if (seleccion == null) return;

        Resumen resumen = newTablaHash.buscarElem(seleccion);
        if (resumen == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el resumen.");
            return;
        }

        StringBuilder resultado = new StringBuilder();
        resultado.append("Nombre del trabajo: ").append(resumen.getTitulo()).append("\n");
        resultado.append("Autores: ");
        String[] autores = resumen.getAutores();
        for (int i = 0; i < autores.length; i++) {
            resultado.append(autores[i]);
            if (i < autores.length - 1) resultado.append(", ");
        }
        resultado.append("\n\n");

        String cuerpo = resumen.getResumen().toLowerCase();
        String[] palabrasClave = resumen.getKeyword();

        for (int i = 0; i < palabrasClave.length; i++) {
            int frecuencia = contarFrecuencia(cuerpo, palabrasClave[i].toLowerCase());
            resultado.append(palabrasClave[i]).append(": aparece ")
                     .append(frecuencia).append(" veces\n");
        }

        JOptionPane.showMessageDialog(this, resultado.toString(), "Análisis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_BotonAnalizarActionPerformed

    private void BotonBuscarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarPCActionPerformed
    String palabraBuscada = JOptionPane.showInputDialog(
        this, 
        "Ingrese la palabra clave para buscar una investigación:",  
        JOptionPane.QUESTION_MESSAGE);

    if (palabraBuscada == null || palabraBuscada.trim().isEmpty()) return;

    String claveEstandarizada = palabraBuscada.trim().toLowerCase();

    // Recorremos todos los resúmenes guardados en newTablaHash
    Lista todos = newTablaHash.obtenerTodos();
    Nodo actual = todos.getHead();
    Lista titulosEncontrados = new Lista();

    while (actual != null) {
        Resumen resumen = (Resumen) actual.getDato();
        String[] keywords = resumen.getKeyword();
        for (String kw : keywords) {
            if (kw.toLowerCase().trim().equals(claveEstandarizada)) {
                titulosEncontrados.addFinal(resumen.getTitulo());
                break; // ya lo encontramos en este resumen
            }
        }
        actual = actual.getNext();
    }

    if (titulosEncontrados.esVacia()) {
        JOptionPane.showMessageDialog(this, 
            "No se encontraron investigaciones con la palabra clave: " + palabraBuscada);
        return;
    }

    // Convertir lista en arreglo
    int cantidad = titulosEncontrados.getSize();
    String[] titulosArray = new String[cantidad];
    Nodo nodo = titulosEncontrados.getHead();
    int i = 0;
    while (nodo != null) {
        titulosArray[i++] = (String) nodo.getDato();
        nodo = nodo.getNext();
    }

    // Selección
    String tituloSeleccionado = (cantidad > 1)
        ? (String) JOptionPane.showInputDialog(this,
            "La palabra '" + palabraBuscada + "' aparece en " + cantidad + " investigaciones.\nSeleccione una:",
            "Resultados de Búsqueda",
            JOptionPane.QUESTION_MESSAGE,
            null,
            titulosArray,
            titulosArray[0])
        : titulosArray[0];

    if (tituloSeleccionado == null) return;

    // Buscar resumen completo por título
    Resumen resumen = newTablaHash.buscarElem(tituloSeleccionado);
    if (resumen == null) {
        JOptionPane.showMessageDialog(this, "No se encontró el resumen para el título seleccionado.");
        return;
    }

    // Mostrar detalles
    StringBuilder detalle = new StringBuilder();
    detalle.append("Título: ").append(resumen.getTitulo()).append("\n");
    detalle.append("Autores: ");
    String[] autores = resumen.getAutores();
    for (int j = 0; j < autores.length; j++) {
        detalle.append(autores[j]);
        if (j < autores.length - 1) detalle.append(", ");
    }
    detalle.append("\n\nResumen:\n").append(resumen.getResumen());

    JOptionPane.showMessageDialog(this, detalle.toString(), 
        "Detalles", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonBuscarPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonAnalizar;
    private javax.swing.JButton BotonBucarAutor;
    private javax.swing.JButton BotonBuscarPC;
    private javax.swing.JButton BotonMPC;
    private javax.swing.JTextField Field1;
    private javax.swing.JTextField Field2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
