/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2.irina.spagnuolo;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Interfaz extends javax.swing.JFrame {
    private HashTable newTablaHash;
    private ArbolPalabrasAVL newArbolPalabras;
    private HashTable tablaPalabrasClave;
    private ArbolAVLAutores arbolAutores;
    private ArbolPalabrasAVL arbolPalabras;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        newTablaHash = new HashTable(200);
        newArbolPalabras = new ArbolPalabrasAVL();
        tablaPalabrasClave = new HashTable(400);
        arbolAutores = new ArbolAVLAutores();
        arbolPalabras = new ArbolPalabrasAVL();
    }
    
    /**
     * Ordena los titulos alfabeticamente
     * @param titulos 
     */
    private void ordenarTitulosABC(String[] titulos) {
        for (int i = 0; i < titulos.length - 1; i++) {
            for (int j = 0; j < titulos.length - i - 1; j++) {
                if (titulos[j].compareToIgnoreCase(titulos[j + 1]) > 0) {
                    String temp = titulos[j];
                    titulos[j] = titulos[j + 1];
                    titulos[j + 1] = temp;
                }
            }
        }
    }
    
    /**
     * Cuenta la frecuencia d ela s palabras
     * @param texto
     * @param palabra
     * @return 
     */
    private int contarFrecuencia(String texto, String palabra) {
        int contador = 0;
        int index = 0;
        while ((index = texto.indexOf(palabra, index)) != -1) {
            contador++;
            index += palabra.length();
        }
        return contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        BotonAnalizar = new javax.swing.JButton();
        BotonBuscarPC = new javax.swing.JButton();
        BotonBucarAutor = new javax.swing.JButton();
        BotonMPC = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Proyecto 2");

        BotonAgregar.setBackground(new java.awt.Color(255, 204, 51));
        BotonAgregar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonAnalizar.setBackground(new java.awt.Color(255, 204, 51));
        BotonAnalizar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonAnalizar.setText("Analizar");
        BotonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalizarActionPerformed(evt);
            }
        });

        BotonBuscarPC.setBackground(new java.awt.Color(255, 153, 0));
        BotonBuscarPC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonBuscarPC.setText("Buscar");
        BotonBuscarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarPCActionPerformed(evt);
            }
        });

        BotonBucarAutor.setBackground(new java.awt.Color(255, 153, 0));
        BotonBucarAutor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonBucarAutor.setText("Buscar");
        BotonBucarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBucarAutorActionPerformed(evt);
            }
        });

        BotonMPC.setBackground(new java.awt.Color(255, 153, 102));
        BotonMPC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BotonMPC.setText("Mostrar palabras clave");
        BotonMPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMPCActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Busca por autor las investigaciones");

        jLabel3.setText("Busca por palabra clave la investigacion");

        jLabel4.setText("Agrega un resumen, tiene que ser un txt");

        jLabel5.setText("Deja que el sistema analize el resumen por ti");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(BotonMPC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBucarAutor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscarPC)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAnalizar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAgregar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(158, 158, 158)
                        .addComponent(Salir)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BotonAgregar))
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BotonAnalizar))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscarPC)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BotonBucarAutor))
                .addGap(11, 11, 11)
                .addComponent(BotonMPC)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed

    AgregarResumen agregarR = new AgregarResumen(newTablaHash);
    Resumen resumen = agregarR.cargarArchivo();
    if (resumen == null) return;

    newTablaHash.agregarElem(resumen);
    for (String autor : resumen.getAutores()) {
        arbolAutores.insertarOActualizar(autor, resumen); 
    }


    JOptionPane.showMessageDialog(this, "Resumen agregado correctamente.");
        
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalizarActionPerformed
        String[] titulos = newTablaHash.obtenerTitulos();
        if (titulos.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay investigaciones guardadas.");
            return;
        }

        ordenarTitulosABC(titulos);

        String seleccion = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione la investigación a analizar:",
            "Analizar investigación",
            JOptionPane.PLAIN_MESSAGE,
            null,
            titulos,
            titulos[0]);

        if (seleccion == null) return;

        Resumen resumen = newTablaHash.buscarElem(seleccion);
        if (resumen == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el resumen.");
            return;
        }

        StringBuilder resultado = new StringBuilder();
        resultado.append("Nombre del trabajo: ").append(resumen.getTitulo()).append("\n");
        resultado.append("Autores: ");
        String[] autores = resumen.getAutores();
        for (int i = 0; i < autores.length; i++) {
            resultado.append(autores[i]);
            if (i < autores.length - 1) resultado.append(", ");
        }
        resultado.append("\n\n");

        String cuerpo = resumen.getResumen().toLowerCase();
        String[] palabrasClave = resumen.getKeyword();

        for (int i = 0; i < palabrasClave.length; i++) {
            int frecuencia = contarFrecuencia(cuerpo, palabrasClave[i].toLowerCase());
            resultado.append(palabrasClave[i]).append(": aparece ")
                     .append(frecuencia).append(" veces\n");
        }

        JOptionPane.showMessageDialog(this, resultado.toString(), "Análisis", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_BotonAnalizarActionPerformed

    private void BotonBuscarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarPCActionPerformed
    String palabraBuscada = JOptionPane.showInputDialog(
        this, 
        "Ingrese la palabra clave para buscar una investigación:",  
        JOptionPane.QUESTION_MESSAGE);

    if (palabraBuscada == null || palabraBuscada.trim().isEmpty()) return;

    String claveEstandarizada = palabraBuscada.trim().toLowerCase();

    Lista todos = newTablaHash.obtenerTodos();
    Nodo actual = todos.getHead();
    Lista titulosEncontrados = new Lista();

    while (actual != null) {
        Resumen resumen = (Resumen) actual.getDato();
        String[] keywords = resumen.getKeyword();
        for (String kw : keywords) {
            if (kw.toLowerCase().trim().equals(claveEstandarizada)) {
                titulosEncontrados.addFinal(resumen.getTitulo());
                break; 
            }
        }
        actual = actual.getNext();
    }

    if (titulosEncontrados.esVacia()) {
        JOptionPane.showMessageDialog(this, 
            "No se encontraron investigaciones con la palabra clave: " + palabraBuscada);
        return;
    }

    /**
     * Convertir lista en arreglo
     */
    int cantidad = titulosEncontrados.getSize();
    String[] titulosArray = new String[cantidad];
    Nodo nodo = titulosEncontrados.getHead();
    int i = 0;
    while (nodo != null) {
        titulosArray[i++] = (String) nodo.getDato();
        nodo = nodo.getNext();
    }

    String tituloSeleccionado = (cantidad > 1)
        ? (String) JOptionPane.showInputDialog(this,
            "La palabra '" + palabraBuscada + "' aparece en " + cantidad + " investigaciones.\nSeleccione una:",
            "Resultados de Búsqueda",
            JOptionPane.QUESTION_MESSAGE,
            null,
            titulosArray,
            titulosArray[0])
        : titulosArray[0];

    if (tituloSeleccionado == null) return;

    Resumen resumen = newTablaHash.buscarElem(tituloSeleccionado);
    if (resumen == null) {
        JOptionPane.showMessageDialog(this, "No se encontró el resumen para el título seleccionado.");
        return;
    }

    StringBuilder detalle = new StringBuilder();
    detalle.append("Título: ").append(resumen.getTitulo()).append("\n");
    detalle.append("Autores: ");
    String[] autores = resumen.getAutores();
    for (int j = 0; j < autores.length; j++) {
        detalle.append(autores[j]);
        if (j < autores.length - 1) detalle.append(", ");
    }
    detalle.append("\n\nResumen:\n").append(resumen.getResumen());

    JOptionPane.showMessageDialog(this, detalle.toString(), 
        "Detalles", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonBuscarPCActionPerformed

    private void BotonBucarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBucarAutorActionPerformed
        String[] listaAutores = arbolAutores.inOrdenArray();
        if (listaAutores.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay autores registrados.");
            return;
        }

        String autorSeleccionado = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione un autor:",
                "Buscar por Autor",
                JOptionPane.PLAIN_MESSAGE,
                null,
                listaAutores,
                listaAutores[0]);

        if (autorSeleccionado == null) return;
        Lista listaTitulos = arbolAutores.buscarTitulos(autorSeleccionado);
        if (listaTitulos == null || listaTitulos.esVacia()) {
            JOptionPane.showMessageDialog(this, "No se encontraron investigaciones para el autor: " + autorSeleccionado);
            return;
        }

        int cantidad = listaTitulos.getSize();
        String[] titulosArray = new String[cantidad];
        Nodo actual = listaTitulos.getHead();
        int i = 0;
        while (actual != null) {
            titulosArray[i++] = (String) actual.getDato();
            actual = actual.getNext();
        }

        String tituloSeleccionado = (cantidad > 1)
            ? (String) JOptionPane.showInputDialog(this,
                "El autor '" + autorSeleccionado + "' participa en " + cantidad + " investigaciones.\nSeleccione una:",
                "Resultados de Búsqueda",
                JOptionPane.QUESTION_MESSAGE,
                null,
                titulosArray,
                titulosArray[0])
            : titulosArray[0];

        if (tituloSeleccionado == null) return;

        Resumen resumen = newTablaHash.buscarElem(tituloSeleccionado);
        if (resumen == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el resumen para el título seleccionado.");
            return;
        }

        StringBuilder detalle = new StringBuilder();
        detalle.append("Título: ").append(resumen.getTitulo()).append("\n");
        detalle.append("Autores: ");
        String[] autores = resumen.getAutores();
        for (int j = 0; j < autores.length; j++) {
            detalle.append(autores[j]);
            if (j < autores.length - 1) detalle.append(", ");
        }
        detalle.append("\n\nResumen:\n").append(resumen.getResumen());

        JOptionPane.showMessageDialog(this, detalle.toString(), 
            "Detalles", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonBucarAutorActionPerformed

    private void BotonMPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMPCActionPerformed
        String[] listaPalabras = arbolPalabras.inOrdenArray();
        if (listaPalabras.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay palabras clave registradas.");
            return;
        }

        String palabraSeleccionada = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione una palabra clave:",
                "Listar Palabras Claves",
                JOptionPane.PLAIN_MESSAGE,
                null,
                listaPalabras,
                listaPalabras[0]);

        if (palabraSeleccionada == null) return;
        Lista listaResúmenes = arbolPalabras.buscarResúmenes(palabraSeleccionada);
        if (listaResúmenes == null || listaResúmenes.esVacia()) {
            JOptionPane.showMessageDialog(this, "No se encontraron investigaciones para la palabra: " + palabraSeleccionada);
            return;
        }
        StringBuilder detalle = new StringBuilder();
        detalle.append("Palabra clave: ").append(palabraSeleccionada).append("\n\n");

        Nodo actual = listaResúmenes.getHead();
        while (actual != null) {
            Resumen resumen = (Resumen) actual.getDato();
            int frecuencia = contarFrecuencia(resumen.getResumen().toLowerCase(), palabraSeleccionada.toLowerCase());
            detalle.append("Título: ").append(resumen.getTitulo())
                   .append(" → aparece ").append(frecuencia).append(" veces\n");
            actual = actual.getNext();
        }

        JOptionPane.showMessageDialog(this, detalle.toString(), "Detalles de palabra clave", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BotonMPCActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        try (PrintWriter pw = new PrintWriter(new FileWriter("resumenes_guardados.txt"))) {
        Lista todos = newTablaHash.obtenerTodos();
        Nodo actual = todos.getHead();
        while (actual != null) {
            Resumen resumen = (Resumen) actual.getDato();
            pw.println("TITULO:" + resumen.getTitulo());
            pw.println("AUTORES:" + String.join(",", resumen.getAutores()));
            pw.println("RESUMEN:" + resumen.getResumen());
            pw.println("PALABRAS:" + String.join(",", resumen.getKeyword()));
            pw.println("----"); 
            actual = actual.getNext();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar los resúmenes: " + e.getMessage());
    }
    System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonAnalizar;
    private javax.swing.JButton BotonBucarAutor;
    private javax.swing.JButton BotonBuscarPC;
    private javax.swing.JButton BotonMPC;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
